apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU190ZmxIT2t1VWwtR2s2dXhCdlhFQG5sdy11bml0ZS1kby11c2VyLTkxMDM2NTktMC5jLmRiLm9uZGlnaXRhbG9jZWFuLmNvbToyNTA2MC9kZWZhdWx0ZGI/c3NsbW9kZT1yZXF1aXJlCg==